# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-28 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reposityory', '0003_auto_20181128_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='hotproject',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='正文'),
        ),
    ]
