# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-29 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xq_type', '0005_types_click_times'),
        ('reposityory', '0005_auto_20181128_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotjob',
            old_name='lable',
            new_name='type_name',
        ),
        migrations.RenameField(
            model_name='hotproject',
            old_name='lable',
            new_name='type_name',
        ),
        migrations.AddField(
            model_name='banner',
            name='type_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='xq_type.Types', verbose_name='标签'),
            preserve_default=False,
        ),
    ]
