# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-28 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coursetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=30, unique=True, verbose_name='课程代码')),
                ('title', models.CharField(max_length=50, verbose_name='课程名')),
                ('credit', models.FloatField(default=0.0, verbose_name='学分')),
                ('period', models.CharField(max_length=10, verbose_name='学时')),
                ('semester', models.CharField(max_length=10, verbose_name='开课学期')),
                ('c_type', models.CharField(max_length=100, verbose_name='课程性质')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('college', models.CharField(max_length=50, verbose_name='学院')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '所有课程',
                'verbose_name_plural': '所有课程',
            },
        ),
        migrations.CreateModel(
            name='MajorSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(max_length=50, verbose_name='学院')),
                ('major', models.CharField(max_length=50, unique=True, verbose_name='专业')),
                ('c_type', models.CharField(max_length=100, verbose_name='课程性质')),
                ('sum_credit', models.FloatField(default=0, verbose_name='总学分')),
            ],
            options={
                'verbose_name': '学分要求',
                'verbose_name_plural': '学分要求',
                'ordering': ['id'],
                'get_latest_by': 'add_time',
            },
        ),
        migrations.CreateModel(
            name='StCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('accomplish', models.FloatField(default=0, verbose_name='已修学分')),
                ('unfinshed', models.FloatField(default=0, verbose_name='未修学分')),
                ('c_type', models.CharField(max_length=100, verbose_name='课程性质')),
            ],
            options={
                'verbose_name': '学生学分管理',
                'verbose_name_plural': '学生学分管理',
            },
        ),
        migrations.CreateModel(
            name='StGgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(max_length=50, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('credit', models.FloatField(default=0.0, verbose_name='学分')),
                ('grade', models.FloatField(default=0.0, verbose_name='成绩')),
                ('c_type', models.CharField(max_length=100, verbose_name='课程性质')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '历年成绩',
                'verbose_name_plural': '历年成绩',
            },
        ),
    ]
