# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-28 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courese', '0002_auto_20181128_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='stggrade',
            name='title',
            field=models.CharField(default=1, max_length=50, verbose_name='课程名'),
            preserve_default=False,
        ),
    ]
