# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-28 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymessage',
            name='gender',
            field=models.CharField(choices=[('男', 'male'), ('女', 'female')], default='男', max_length=6),
        ),
        migrations.AlterField(
            model_name='mymessage',
            name='promote_sys',
            field=models.URLField(blank=True, null=True, verbose_name='助学系统'),
        ),
    ]
