# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-28 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181128_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='myclass',
            field=models.CharField(default=1, max_length=10, verbose_name='班级'),
            preserve_default=False,
        ),
    ]
