# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-30 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181128_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymessage',
            name='grade',
            field=models.CharField(default=1, max_length=20, verbose_name='年级'),
            preserve_default=False,
        ),
    ]
