# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-28 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personal_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_id', models.CharField(default='', max_length=50, verbose_name='学号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('click_times', models.IntegerField(default=0, verbose_name='点击次数')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50, unique=True, verbose_name='类名')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '总分类',
                'verbose_name_plural': '总分类',
            },
        ),
        migrations.AddField(
            model_name='personal_type',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='xq_type.Types', verbose_name='类名'),
        ),
    ]
