# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-28 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xq_type', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal_type',
            options={'verbose_name': '个人分类', 'verbose_name_plural': '个人分类'},
        ),
        migrations.AddField(
            model_name='types',
            name='desc',
            field=models.TextField(default='', verbose_name='描述'),
        ),
    ]
