# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-11-28 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xq_type', '0003_auto_20181128_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
